# Generated by Django 4.1 on 2022-11-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequestDetails',
            fields=[
                ('visitid', models.AutoField(db_column='VisitID', primary_key=True, serialize=False)),
                ('location', models.CharField(db_column='Location', max_length=100)),
                ('visitstartdatetime', models.DateTimeField(db_column='VisitStartDateTime')),
                ('visitenddatetime', models.DateTimeField(db_column='VisitEndDateTime')),
                ('visitstatus', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Revision')], db_column='VisitStatus', max_length=8)),
                ('additionalcomments', models.TextField(blank=True, db_column='AdditionalComments', null=True)),
                ('maplink', models.CharField(blank=True, db_column='MapLink', max_length=100, null=True)),
                ('certifiedbyemail', models.CharField(db_column='CertifiedByEmail', max_length=100)),
                ('certifiedbyname', models.CharField(db_column='CertifiedByName', max_length=100)),
                ('createdbyemail', models.EmailField(db_column='CreatedByEmail', max_length=100)),
            ],
            options={
                'db_table': 'VisitRequestDetails',
                'managed': False,
            },
        ),
    ]
